### ISSUE TITLE
I want a GET with "name_tag_sheet_type"

### ISSUE THREAD

**Issue by Zettir** [groskopf/printerbox_pdf#19]

**Comment by Zettir** [comment]
`async function getImages() {
    var requestOptions = {
        method: 'GET', // *GET, POST, PUT, DELETE, etc.
        mode: 'no-cors', // no-cors, *cors, same-origin
        cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
        credentials: 'same-origin', // include, *same-origin, omit
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'Access-Control-Request-Method': 'GET'
        },
        //redirect: 'follow', // manual, *follow, error
        referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
        body: JSON.stringify(requestOptions) // body data type must match "Content-Type" 
    };

    let getImagesRequest = await fetch('https://api.printerboks.dk/api/v1/upload/images', requestOptions)
    .then(response => response)
    .then(result => console.log(result))
    .catch(error => console.log('error', error))
}`

**Comment by groskopf** [comment]
Fixed by enabling CORS
